<a href="https://colab.research.google.com/github/shawnkikule/AI-CLUB-TUTORIALS/blob/main/AIClubNumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python libraries play a crucial role in machine learning by providing a wide range of tools and functionalities that simplify the development, implementation, and deployment of machine learning models.
The most popular of these libraries are;
- Numpy
- Pandas
- Matplotlib
- Sci-kit learn
- Seaborn ... to mention but a few

Today we'll going through an Numpy.
NB: This isn't an exhaustive tutorial on Numpy, just enough get you to know the basics and the most common aplications in Machine Learning.

Compiled by KikuleShawnJ

##WHAT IS NUMPY

Numpy(Numerical Python) is a Python library for creating and manipulating matrices, the main data structure used by Machine Learning algorithms. Matrices are mathematical objects used to store values in rows and columns.

Python calls matrices lists, NumPy calls them arrays and TensorFlow calls them tensors. Python represents matrices with the list data type.

It provides efficient N-dimensional array objects, mathematical functions, linear algebra operations, and random number generation. NumPy is the backbone of many other libraries in the scientific computing and machine learning ecosystem.


##IMPORT NumPy MODULE

Run the code cells below to import NumPy and check the version.


In [ ]:
import numpy


In [ ]:
# install numpy
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# import numpy and give it the alias np
import numpy as np

In [ ]:
# check your numpy version being used
np.__version__

'1.22.4'

##POPULATING NUMPY ARRAYS SPECIFIC NUMBERS
We use `np.array` to create numpy arrays with your own values.
You can specify the datatype using `dtype` argument(The default is int64).
The code cell below creates a 5 element array, whose elements are of type 'float32':

In [ ]:
one_dimensional_array = np.array([2.7, 3.5, 4.6, 5.2, 6.1], dtype='float32') # 1x1 array
array2 = np.array([2,3,4,5])
datatype = array2.dtype
print(datatype)
# print(one_dimensional_array)
# print(type(one_dimensional_array))
# using ndim to check for the number of dimensions in the array

int64


You can also create a two dimensional array in the same way, just by adding a layer of square brackets. The code cell below creates a 3x2 numpy array.

In [ ]:
two_dimensinal_array = np.array([

    [4.7, 6.8, 3],
    [8.9, 8.4, 9],
    [5.3, 7.4, 8]

    ])

print(two_dimensinal_array)

[[4.7 6.8 3. ]
 [8.9 8.4 9. ]
 [5.3 7.4 8. ]]


In [ ]:
three_dimensional_array = np.array(
    [
        [
            [4,5,7],[3,5,3]
        ],
        [
            [7,9,2],[8,5,4]
        ],
      [[5.5,6.6],[5,7,9]]])
print(three_dimensional_array)


[[[4.  5.  7. ]
  [7.  9.  2. ]
  [5.5 6.6 8.7]]]


You can also populate populate a numpy array specifically with zero's and one's

In [ ]:
print(np.zeros(6))
print(np.ones(6))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


## POPULATING NUMPY ARRAYS WITH A SEQUENCE OF NUMBERS
You can populate the arrays with a sequence of numbers from a specific lower bound, to a specific upper bound

In [ ]:
sequence_of_intergers = np.arange(5,12)
print(sequence_of_intergers)


[ 5  6  7  8  9 10 11]


In [ ]:
integer_sequence_2 = np.arange(2,11,2)
print(integer_sequence_2)

[ 2  4  6  8 10]


##POPULATING NUMPY ARRAYS WITH RANDOM NUMBERS
NumPy provides many functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 5-element array with random integers between 1 and 50.

In [ ]:
random_array = np.random.randint(low=1, high=51, size=(5))
print(random_array)

[ 7  6 41 19  2]


You can also create an array of random floating point numbers using `np.random.random` between 0 and 1.

In [ ]:
random_float_between_0and1 = np.random.random([6])
print(random_float_between_0and1)

[0.30328029 0.03403788 0.36126116 0.20180599 0.41602207 0.70554418]


In [ ]:
# random floating point numbers between 2 and 4
random_fp = np.random.uniform(2,4, size=10)
print(random_fp)

[3.17947098 3.20432784 2.34139667 2.79420208 3.17061984 2.71764789
 3.34656264 2.01420953 2.2544191  3.07002899]


##MATHEMATICAL OPERATIONS ON NUMPY OPERANDS
NumPy uses a technique called broadcasting to simplfy addition, subtraction and multiplication of NumPy operands as illustrated in the code cell below.

In [ ]:
# generating data_set we will use for broadcasting
broadcasting_arr = np.random.randint(low=50, high=101, size=(10))
print(broadcasting_arr)


[70 83 77 84 76 59 65 67 85 97]


In [ ]:
# addition
added = broadcasting_arr + 3
print(added)

[ 73  86  80  87  79  62  68  70  88 100]


In [ ]:
# subtraction
subtracted = broadcasting_arr - 3
print(subtracted)

[67 80 74 81 73 56 62 64 82 94]


In [ ]:
# multiplication
multiplied = broadcasting_arr * 2
print(multiplied)

[140 166 154 168 152 118 130 134 170 194]


##TASK 1
Create a simple dataset consisting of a simplefeature and label as follows:
1. Assign a sequence of integers from 5 to 20(inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label`, such that:
```
label = (2)feature + 4
```
for example, the first value in label should be;
```
label (2)(5) + 4 = 14
```

In [ ]:
feature = np.arange(5,21, dtype='float32')
print(feature)

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [ ]:
label = feature * 2
label += 4
print(label)

[14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.]


##TASK 2
Randomize your dataset by adding different random floating point numbers between -4 and 4 to the `label` dataset.

Hint : Do not rely on broadcasting, create a different array with the same dimensions as the label array then add the two.

In [ ]:
noise = np.random.uniform(low=-4, high=4, size=16)
print(noise)
label += noise
print(label)

[ 0.5568719   0.31587075 -3.25532852  0.38810523 -2.78119993  0.2125181
 -1.38382142  3.7633882   1.21208514  2.40212878  3.43393631  1.59290814
 -2.22852182  1.93416227  2.69754171  2.8298152 ]
[14.556872 16.31587  14.744672 20.388105 19.2188   24.212519 24.616179
 31.763388 31.212086 34.40213  37.433937 37.592907 35.771477 41.934162
 44.69754  46.829815]


## ARRAY INDEXING
You can access elements of an array using their index numbers, indices start from 0, and the second index has 1, and so on.


In [ ]:
indexing_array = np.array([1,2,3,4,5])
# getting a specific element
print(indexing_array[3])
# mathematical operations on elements
print(indexing_array[3]+indexing_array[2])

4
7


ACCESSING 2D ARRAYS

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.



In [ ]:
twoD_array = np.array([[1,2,3,4],[5,6,7,8]])
print(twoD_array[0,3])
print(twoD_array[1,1])

4
6


ACCESSING 3D ARRAYS

To access elements from 3D arrays is similar

In [ ]:
threeD = np.array([[[3,2,4,5], ]])